services:
  frontend-service:
    container_name: frontend
    image: frontend 
    build: 
      context: ./example-frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend-service
    networks:
      - service-network

  backend-service:
    container_name: backend
    image: backend
    build:
      context: ./example-backend
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - service-network

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - service-network

networks:
  service-network:
    driver: bridge