name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./6. DevOps with Docker (part 3)/ex3.1/express-app             
          file: ./express-app/Dockerfile    
          tags: ${{ secrets.DOCKER_USERNAME }}/express-app:latest
